services:
  backend:
    image: andrews326/aureole-backend:v1
    container_name: aureole-backend
    ports:
      - "8000:8000"
    env_file:
      - /home/ubuntu/app/.env  # Absolute path to the .env file
    depends_on:
      - db
    restart: always
    networks:
      - aureole
    entrypoint: /entrypoint.sh

  frontend:
    image: andrews326/aureole-frontend:v1
    container_name: aureole-frontend
    env_file:
      - /home/ubuntu/interface/.env  # Absolute path to the .env file
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
    networks:
      - aureole

  db:
    image: ankane/pgvector:latest
    container_name: aureole-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aureole
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    ports:
      - "5432:5432"
    restart: always
    networks:
      - aureole
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aureole || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  aureole:
