version: "3.9"

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: aureole-backend
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db
    restart: always
    networks:
      - aureole
    entrypoint: /entrypoint.sh  # Use entrypoint script for migrations and app start

  frontend:
    build:
      context: ./interface
      dockerfile: Dockerfile
    container_name: aureole-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
    networks:
      - aureole

  db:
    image: ankane/pgvector:latest
    container_name: aureole-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aureole
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql  # Mount script here

    ports:
      - "5432:5432"  # Use the default Postgres port
    restart: always
    networks:
      - aureole

volumes:
  pgdata:

networks:
  aureole:
